### ISSUE TITLE
Site doesn't render with liquid-fire - 0.24.0

### ISSUE THREAD

**Issue by jurecuhalev** [ember-fastboot/fastboot-website#50]
When I try to run site in browser or in fastboot, I get:

```
➜  fastboot-website git:(master) ember fastboot --serve-assets
Installing FastBoot npm dependencies

Build successful - 3530ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
PostcssCompiler                               | 311ms               
AutoprefixerFilter                            | 228ms               
PostcssCompiler                               | 208ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (34)                                    | 733ms (21 ms)       
PostcssCompiler (2)                           | 520ms (260 ms)      
SourceMapConcat: Concat: Vendor /asset... (2) | 286ms (143 ms)      
AutoprefixerFilter (2)                        | 271ms (135 ms)      
TemplateCompiler (8)                          | 234ms (29 ms)       

There was an error trying to run your application in FastBoot.

This is usually caused by either your application code or an addon trying to access an API that isn't available in Node.js.
Based on the stack trace, it looks like the exception was generated in dist/fastboot/vendor.js on line 10611.
Because it's coming from vendor.js, an addon is most likely responsible for this error. You should look at this file and line number to determine which addon is not yet FastBoot compatible.

The full stack trace is:

Could not find module htmlbars-runtime
Error: Could not find module htmlbars-runtime
    at missingModule (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:10611:15)
    at internalRequire (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:10633:9)
    at requireModule (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:10597:14)
    at Module.callback (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:100765:50)
    at Module.exports (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:140:32)
    at Module._reify (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:173:59)
    at Module.reify (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:159:27)
    at Module.exports (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:138:10)
    at requireModule (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:32:18)
    at /Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:97996:20
    at Array.forEach (native)
    at exports.default (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:97993:8)
    at Module.callback (/Users/gandalf/build/fastboot-website/dist/fastboot/fastboot-website.js:21:41)
    at Module.exports (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:140:32)
    at Module._reify (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:173:59)
    at Module.reify (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:159:27)
    at Module.exports (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:138:10)
    at Object.requireModule (/Users/gandalf/build/fastboot-website/dist/fastboot/vendor.js:32:18)
    at Object.<anonymous> (/Users/gandalf/build/fastboot-website/node_modules/fastboot/dist/cjs/ember-app.js:160:18)
    at Sandbox.VMSandbox.run (/Users/gandalf/build/fastboot-website/node_modules/fastboot/dist/cjs/vm-sandbox.js:18:13)
    at EmberApp.createEmberApp (/Users/gandalf/build/fastboot-website/node_modules/fastboot/dist/cjs/ember-app.js:159:30)
    at EmberApp.retrieveSandboxedApp (/Users/gandalf/build/fastboot-website/node_modules/fastboot/dist/cjs/ember-app.js:184:17)
    at new EmberApp (/Users/gandalf/build/fastboot-website/node_modules/fastboot/dist/cjs/ember-app.js:48:21)
    at FastBoot._buildEmberApp (/Users/gandalf/build/fastboot-website/node_modules/fastboot/dist/cjs/index.js:111:17)
    at new FastBoot (/Users/gandalf/build/fastboot-website/node_modules/fastboot/dist/cjs/index.js:52:10)
    at fastbootExpressMiddleware (/Users/gandalf/build/fastboot-website/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/index.js:24:16)
    at exec.then (/Users/gandalf/build/fastboot-website/node_modules/ember-cli-fastboot/lib/tasks/fastboot-server.js:34:71)
    at tryCatch (/Users/gandalf/build/fastboot-website/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/gandalf/build/fastboot-website/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/gandalf/build/fastboot-website/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/gandalf/build/fastboot-website/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Upgrading liquidfire to:
```"liquid-fire": "0.27.0",```

makes the site build correctly.

DEBUG: Ember : 2.10.2
ember-cli: 2.6.2
node: 6.9.2
os: darwin x64

If this makes sense, I can do a PR to bump dependency.

**Comment by jurecuhalev** [comment]
While testing this again, it seems that it doesn't actually work. I'm not sure why it worked with my branch at all. Right now, doing a clean checkout and running fastboot twice, I get the following crash:


```
➜  fastboot-website git:(fix-issue-50) ember fastboot --serve-assets
Installing FastBoot npm dependencies

Build successful - 10007ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Babel                                         | 2753ms              
Babel                                         | 889ms               
Babel                                         | 743ms               
Babel                                         | 732ms               
Babel                                         | 597ms               
PostcssCompiler                               | 504ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (34)                                    | 6748ms (198 ms)     
PostcssCompiler (2)                           | 716ms (358 ms)      

There was an error trying to run your application in FastBoot.

This is usually caused by either your application code or an addon trying to access an API that isn't available in Node.js.
Based on the stack trace, it looks like the exception was generated in util.js on line 1022.
The exception is probably coming from your app. Look at this file and line number to determine what is triggering the exception.

The full stack trace is:

spawn /bin/sh ENOENT
Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
^C%                                                                                                                                                                        ➜  fastboot-website git:(fix-issue-50) ember fastboot --serve-assets
Installing FastBoot npm dependencies

Build successful - 3154ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
PostcssCompiler                               | 316ms               
AutoprefixerFilter                            | 220ms               
PostcssCompiler                               | 203ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (34)                                    | 623ms (18 ms)       
PostcssCompiler (2)                           | 520ms (260 ms)      
SourceMapConcat: Concat: Vendor /asset... (2) | 279ms (139 ms)      
AutoprefixerFilter (2)                        | 251ms (125 ms)      
TemplateCompiler (8)                          | 193ms (24 ms)       

DEBUG: -------------------------------
DEBUG: Ember : 2.10.2
DEBUG: -------------------------------
Ember FastBoot running at http://[::]:3000
DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]
        at logDeprecationStackTrace (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:16098:19)
        at HANDLERS.(anonymous function) (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:16209:7)
        at raiseOnDeprecation (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:16128:12)
        at HANDLERS.(anonymous function) (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:16209:7)
        at invoke (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:16225:7)
        at deprecate (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:16193:32)
        at Object.deprecate (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:27212:37)
        at Module.callback (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:97984:21)
        at Module.exports (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:140:32)
        at Module._reify (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:173:59)
        at Module.reify (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:159:27)
        at Module.exports (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:138:10)
        at Module._reify (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:173:59)
        at Module.reify (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:159:27)
        at Module.exports (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:138:10)
        at requireModule (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:32:18)
        at Class._extractDefaultExport (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:99038:20)
        at Class.resolveOther (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:98751:32)
        at Class.superWrapper (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:50189:22)
        at Class.resolve (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:15603:35)
        at resolve (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:12998:36)
        at Object.resolve (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:12457:21)
        at Object.resolve (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:12461:55)
        at has (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:13015:21)
        at Object.has (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:12549:14)
        at Object.validateInjections (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:12858:19)
        at /Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:12094:30
        at runInDebug (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:16381:5)
        at Object.runInDebug (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:27220:38)
        at instantiate (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:12088:19)
        at lookup (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:11941:17)
        at Object.lookup (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:11860:14)
        at Class.lookup (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:42326:33)
        at Class.<anonymous> (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:13417:19)
        at ComputedPropertyPrototype.get (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:26852:28)
        at Object.get (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:31759:19)
        at Class._bootSync (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:13397:34)
        at /Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:14813:30
        at initializePromise (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:68766:5)
        at new Promise (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:69251:31)
        at Class.boot (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:14812:27)
        at /Users/gandalf/build/site2/fastboot-website/node_modules/fastboot/dist/cjs/ember-app.js:235:25
        at tryCatch (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:68718:12)
        at invokeCallback (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:68730:13)
        at publish (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:68701:7)
        at /Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:48186:16
        at invokeWithOnError (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:10901:16)
        at Object.flush (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:10960:9)
        at Object.flush (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:11084:15)
        at Object.end (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:11154:23)
        at Timeout._onTimeout (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:11720:16)
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)
2016-12-26T19:50:38.631Z 500 Unknown Error: Error: Assertion Failed: EventDispatcher should never be instantiated in fastboot mode. Please report this as an Ember bug.
    at assert (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:16268:13)
    at Object.assert (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:27196:34)
    at Class.init (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:51446:19)
    at Class.superWrapper [as init] (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:50189:22)
    at new Class (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:45879:17)
    at Function.create (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:46167:14)
    at instantiate (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:12104:23)
    at lookup (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:11941:17)
    at Object.lookup (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:11860:14)
    at Class.lookup (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:42326:33)
    at /Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:17515:59
    at Class.init (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:17525:9)
    at Class.superWrapper [as init] (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:50189:22)
    at new Class (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:45879:17)
    at Function.create (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:46167:14)
    at Object.initialize (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/fastboot-website.js:450:38)
    at /Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:15130:21
    at Vertices.each (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:13183:13)
    at Vertices.topsort (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:13150:14)
    at DAG.topsort (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:13095:24)
    at Class._runInitializer (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:15145:13)
    at Class.runInstanceInitializers (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:15128:12)
    at Class._bootSync (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:13401:24)
    at /Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:14813:30
    at initializePromise (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:68766:5)
    at new Promise (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:69251:31)
    at Class.boot (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:14812:27)
    at /Users/gandalf/build/site2/fastboot-website/node_modules/fastboot/dist/cjs/ember-app.js:235:25
    at tryCatch (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:68718:12)
    at invokeCallback (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:68730:13)
    at publish (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:68701:7)
    at /Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:48186:16
    at invokeWithOnError (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:10901:16)
    at Object.flush (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:10960:9)
    at Object.flush (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:11084:15)
    at Object.end (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:11154:23)
    at Timeout._onTimeout (/Users/gandalf/build/site2/fastboot-website/dist/fastboot/vendor.js:11720:16)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

```

ember-cli: 2.6.2
node: 6.9.2
os: darwin x64

**Comment by john-griffin** [comment]
Getting the same error here with `util.js on line 1022`.

ember-cli: 2.11.0
node: 6.9.2
os: darwin x64
